<?php

use App\Actions\Catalog\SearchCatalog;
use App\Models\CatalogItem;
use App\Models\ProductLine;
use App\Models\Set;
use App\Models\Vertical;

/**
 * Telling two printings of one card apart.
 *
 * Lorcana prints every card normal and foil, and both are real rows that trade
 * at different prices — the foil carries a premium of about 1.4x. They share a
 * name, a collector number and an image, because catalogs publish one scan per
 * card, so the printing label is the only thing separating them on screen.
 *
 * It used to be shown on the foil only, leaving its sibling blank, which made a
 * set listing look like every card was in the catalog twice.
 */
beforeEach(function () {
    $vertical = Vertical::firstOrCreate(['slug' => 'tcg'], ['name' => 'Trading Card Games']);
    $line = ProductLine::factory()->create(['vertical_id' => $vertical->id, 'slug' => 'lorcana']);
    $this->set = Set::factory()->create(['product_line_id' => $line->id, 'slug' => 'the-first-chapter']);
    $this->line = $line;
    $this->vertical = $vertical;
});

/**
 * Built through the real action, not the factory.
 *
 * base_key is what groups printings, and only CreateCatalogItem computes it —
 * a factory row leaves it null, the relation joins on null, and the count comes
 * back zero however many siblings exist.
 */
function printing(object $ctx, string $variant): CatalogItem
{
    return app(\App\Actions\Catalog\CreateCatalogItem::class)(
        vertical: $ctx->vertical,
        productLine: $ctx->line,
        set: $ctx->set,
        itemType: \App\Enums\ItemType::Single,
        name: 'Elsa - Spirit of Winter',
        number: '42',
        attributes: ['language' => 'en', 'variant' => $variant],
    );
}

test('a card with two printings reports the count on both rows', function () {
    printing($this, 'normal');
    printing($this, 'foil');

    $results = app(SearchCatalog::class)(['set' => $this->set->slug]);
    $items = collect($results->items());

    expect($items)->toHaveCount(2)
        // Both, not just the foil: the label is drawn from this, and a row that
        // reports nothing renders as an unlabelled duplicate.
        ->and($items->pluck('variants_count')->all())->toBe([2, 2]);
});

test('a card with one printing reports one, so no label is drawn', function () {
    printing($this, 'normal');

    $results = app(SearchCatalog::class)(['set' => $this->set->slug]);

    // Stamping "Normal" on every card in the catalog would be noise.
    expect(collect($results->items())->first()->variants_count)->toBe(1);
});

test('the two printings are separate rows with their own prices', function () {
    // The reason this is a label problem and not a duplicate problem: foil is a
    // distinct printing that trades at a premium, deliberately generated by
    // catalog:generate-foils.
    $normal = printing($this, 'normal');
    $foil = printing($this, 'foil');

    expect($normal->id)->not->toBe($foil->id)
        ->and($normal->identity_hash)->not->toBe($foil->identity_hash)
        // Same base card, so they group together.
        ->and($normal->base_key)->toBe($foil->base_key);
});
